camera_monitor:
  ros__parameters:
    num_cameras: 2
    capture_interval_ms: 100
    individual_topics: true
    fps: 15
    encoding: "bgr8"
    CAM1:
      serial_id: 1
      fps: 30
    CAM2:
      serial_id: 2
      fps: 25
    camera_topics:
      - "/camera1"
      - "/camera2"
    merged_feed: "/merged_cameras"
